import img from "../../../assets/Blog/BlogSection/light-bulbs-1407610_640.jpg";

const tips = [
  { id: 1, title: "Cambia a mejores bombillas", imgSrc: img },
  { id: 2, title: "Renueva tus filtros de aire", imgSrc: img },
  { id: 3, title: "Haz descansar tu máquina secadora", imgSrc: img },
  { id: 4, title: "Prefiere a las baterías recargables", imgSrc: img },
  { id: 5, title: "Cultiva tú mismo", imgSrc: img },
  { id: 6, title: "Desconecta tus dispositivos", imgSrc: img },
  { id: 7, title: "Recicla tus residuos electrónicos", imgSrc: img },
  { id: 8, title: "Utiliza bolsas reutilizables", imgSrc: img },
  { id: 9, title: "Compra productos locales", imgSrc: img },
  { id: 10, title: "Reduce el consumo de agua", imgSrc: img },
  { id: 11, title: "Opta por energías renovables", imgSrc: img },
  { id: 12, title: "Aprovecha la luz natural", imgSrc: img },
  { id: 13, title: "Composta tus residuos orgánicos", imgSrc: img },
  { id: 14, title: "Elige productos con menos empaques", imgSrc: img },
  { id: 15, title: "Reduce el uso de plásticos", imgSrc: img },
  { id: 16, title: "Utiliza electrodomésticos eficientes", imgSrc: img },
  { id: 17, title: "Participa en limpiezas comunitarias", imgSrc: img },
  { id: 18, title: "Recoge y recicla papel", imgSrc: img },
  { id: 19, title: "Promueve el uso de transporte público", imgSrc: img },
  { id: 20, title: "Instala grifos ahorradores de agua", imgSrc: img },
  { id: 21, title: "Haz reparaciones en lugar de reemplazar", imgSrc: img },
  {
    id: 22,
    title: "Utiliza ventiladores en lugar de aire acondicionado",
    imgSrc: img,
  },
  { id: 23, title: "Reutiliza envases de vidrio", imgSrc: img },
  { id: 24, title: "Compra en mercados de segunda mano", imgSrc: img },
  { id: 25, title: "Promueve el uso de bicicletas", imgSrc: img },
  { id: 26, title: "Reduce el desperdicio de comida", imgSrc: img },
  { id: 27, title: "Utiliza productos de limpieza ecológicos", imgSrc: img },
  {
    id: 28,
    title: "Opta por productos con certificados ecológicos",
    imgSrc: img,
  },
  { id: 29, title: "Haz uso eficiente del papel", imgSrc: img },
  { id: 30, title: "Participa en programas de reciclaje", imgSrc: img },
  { id: 31, title: "Desconecta cargadores cuando no se usan", imgSrc: img },
  {
    id: 32,
    title: "Utiliza herramientas manuales cuando sea posible",
    imgSrc: img,
  },
  { id: 33, title: "Compra productos a granel", imgSrc: img },
  {
    id: 34,
    title: "Realiza mantenimiento preventivo a tus electrodomésticos",
    imgSrc: img,
  },
  {
    id: 35,
    title: "Conserva la energía apagando luces innecesarias",
    imgSrc: img,
  },
  { id: 36, title: "Sustituye bombillas incandescentes por LED", imgSrc: img },
  { id: 37, title: "Usa agua fría para lavar ropa", imgSrc: img },
  {
    id: 38,
    title: "Asegúrate de que las ventanas estén bien selladas",
    imgSrc: img,
  },
  { id: 39, title: "Realiza compras responsables y planificadas", imgSrc: img },
  { id: 40, title: "Planta árboles en tu comunidad", imgSrc: img },
  { id: 41, title: "Opta por productos de madera sostenible", imgSrc: img },
  { id: 42, title: "Fomenta el uso de materiales reciclados", imgSrc: img },
  { id: 43, title: "Haz uso eficiente de la calefacción", imgSrc: img },
  { id: 44, title: "Reduce el uso de productos desechables", imgSrc: img },
  {
    id: 45,
    title: "Participa en iniciativas de ahorro energético",
    imgSrc: img,
  },
  { id: 46, title: "Promueve el uso de energía solar", imgSrc: img },
  { id: 47, title: "Recicla correctamente los residuos de papel", imgSrc: img },
  { id: 48, title: "Utiliza cortinas que bloqueen el calor", imgSrc: img },
  {
    id: 49,
    title: "Haz una revisión periódica de tus hábitos de consumo",
    imgSrc: img,
  },
  {
    id: 50,
    title: "Involucra a tu familia en prácticas sostenibles",
    imgSrc: img,
  },
];

export default tips;
